/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as devTokenSol from "./devToken.sol";
export type { devTokenSol };
export type { QuizNFT } from "./QuizNFT";
export type { YourContract } from "./YourContract";
